FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

# System deps (optional but helpful for SSL, timezones)
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates tzdata && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir requests

COPY src/m3u-gen/app ./app

# Run script
CMD ["python", "app/main.py"]
